[package]
name = "cofi"
version = "0.1.1"
authors = ["Vsevolod Zubarev <vsevolod.zubarev@veeam.com>"]

[dependencies]
error-chain = "0.11.0" 
rand = "0.3"
md5 = "0.3.5"
winapi = "0.2.8"

[profile.release]
debug = true