[package]
name = "cofi"
version = "0.3.1"
authors = ["Vsevolod Zubarev <vsevolod.zubarev@veeam.com>"]
edition = "2018"

[dependencies]
rand = "0.7.2"
md5 = "0.7.0"
winapi = { version = "0.3.8", features = ["winbase"] }
log = "0.4.8"
fern = "0.5.9"
chrono = "0.4.10"
libc = "0.2.66"
failure = "0.1.6"
num_cpus = "1.11.1"
crossbeam-channel = "0.4.0"
clap = "2.33.0"
indicatif = "0.13.0"
