[package]
name = "cofi"
version = "0.1.4"
authors = ["Vsevolod Zubarev <vsevolod.zubarev@veeam.com>"]

[dependencies]
error-chain = "0.12.0"
rand = "0.5.5"
md5 = "0.4.0"
winapi = { version = "0.3.5", features = ["winbase"] }
log = "0.4.5"
fern = "0.5.6"
chrono = "0.4.6"
libc = "0.2.43"

[profile.release]
debug = true
