[package]
name = "cofi"
version = "0.3.1"
authors = ["Vsevolod Zubarev <vsevolod.zubarev@veeam.com>"]
edition = "2018"

[dependencies]
rand = "0.6.5"
md5 = "0.6.1"
winapi = { version = "0.3.7", features = ["winbase"] }
log = "0.4.6"
fern = "0.5.8"
chrono = "0.4.6"
libc = "0.2.55"
failure = "0.1.5"
num_cpus = "1.10.0"
crossbeam-channel = "0.3.8"
clap = "2.33.0"
indicatif = "0.11.0"
