[package]
name = "cofi"
version = "0.1.4"
authors = ["Vsevolod Zubarev <vsevolod.zubarev@veeam.com>"]

[dependencies]
error-chain = "0.12.0"
rand = "0.6.5"
md5 = "0.6.1"
winapi = { version = "0.3.6", features = ["winbase"] }
log = "0.4.6"
fern = "0.5.7"
chrono = "0.4.6"
libc = "0.2.50"
