[package]
name = "cofi"
version = "0.1.4"
authors = ["Vsevolod Zubarev <vsevolod.zubarev@veeam.com>"]

[dependencies]
error-chain = "0.11.0"
rand = "0.3"
md5 = "0.3.5"
winapi = "0.2.8"
log = "0.3"
fern = "0.4"
chrono = "0.4.0"
libc = "0.2.32"

[profile.release]
debug = true